### ISSUE TITLE
Filters should work like in Athena

### ISSUE THREAD

**Issue by pjlammertyn** [RADar-AZDelta/azd-radar-data-athenaSearch#4]
All filters hould be visable.
A filter should be greyed out, when it is not in the search results.

![image](https://github.com/RADar-AZDelta/svelte-Athena-search/assets/1187178/c8ca9e22-468c-4a90-b6ed-8e0dba535873)

vs

![image](https://github.com/RADar-AZDelta/svelte-Athena-search/assets/1187178/463353f2-b33e-43b3-b67c-9d620272cb05)

**Comment by BostoenToby** [comment]
TODO:
- [x] Disable filters that are not in the search results
- [x] Sort filters to show useable filters first
